Update ecmaVersion to 'latest' in esnext.js in eslint-plugin to ensure it's esnext.
Shopify/web-configs pull request #296
Opened 2021-10-22 02:54 UTC by iamyoki

## Description
This PR updates a simple config in esnext.js in eslint-plugin, it prevents some potential problems.
It updates
```js
  parserOptions: {
    ecmaVersion: '2018',
    sourceType: 'module',
  }
```
to
```js
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
  }
```
so to ensure it always be esnext latest version.

Here is the official docs mentioned: https://eslint.org/docs/user-guide/configuring/language-options#specifying-parser-options.

Also updates env `es6` to `es2021`.

## Type of change

- [x]  Patch: Bug (non-breaking change which fixes an issue)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [ ]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have added a changelog entry, prefixed by the type of change noted above (Documentation fix and Test update does not need a changelog as we do not publish a new version for these changes)

2021-11-11 19:25 UTC, lucabezerra commented
@iamyoki I think you added it twice by mistake, heh :)

2021-11-16 18:45 UTC, BPScott requested changes
`latest` isn't supported in our the parsers versions that we currently require.

Let's have use `ecmaVersion: 2021` to get us onto the latest version in this PR

Then if you're feeling a brave, open new PRs for replacing `babel-eslint` with `@babel/eslint-parser`, and updating `@typescript-eslint/parser` to the latest version in the v4 branch (we'll want to go to v5 at some point but perhaps we should do that as part of the plugin updates required to support eslint v8).

2021-11-16 18:45 UTC, BPScott commented on packages/eslint-plugin/lib/config/esnext.js
> +    ecmaVersion: 'latest',
```suggestion
    ecmaVersion: '2021',
```

`latest` doesn't seem to be supported in the parsers that we currently use. Let's keep this as `2021`, and look at using `latest` once we're using parsers that support it.

- We use `@typescript-eslint/parser@^4.28.2` however support for ecmaVersion 'latest' was added in [v4.32.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.32.0)
- We use the long-deprecated `babel-eslint` however  support for ecmaVersion 'latest' was added in it's successor `@babel/eslint-parser` in [v7.15.4](https://github.com/babel/babel/pull/13638)

2021-11-26 16:36 UTC, BPScott approved these changes

2021-11-26 16:36 UTC, merged