[Unified Admin] Restrict /admin in Route path literals and templates
Shopify/web-configs pull request #315
Opened 2022-01-10 16:40 UTC by ttemrahcelik

## Description

We are on our way to remove the path prefix `/admin` as part of Unified Admin project.
The prefix is being extracted into a global state/variable to be shared across web as much as we can.
In the meantime, we draw the line with this rule so we don't keep adding routes with the hardcoded prefix.

## Type of change

- [ ]  Patch: Bug (non-breaking change which fixes an issue)
- [ ]  Minor: New feature (non-breaking change which adds functionality)
- [x]  Major: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above (Documentation fix and Test update does not need a changelog as we do not publish a new version for these changes)

2022-01-12 01:47 UTC, BPScott commented
This stuff is all seems very web-specific. Does this have use outside of the web repository?

I wonder if we should be putting web-specific rules directly in the web repository

2022-01-12 13:32 UTC, ttemrahcelik commented
> This stuff is all seems very web-specific. Does this have use outside of the web repository?
> 
> I wonder if we should be putting web-specific rules directly in the web repository

The stuff I'm adding is only for web.

You mean moving this whole project to web, or only what I'm adding?

And may I ask where we add these rules to web?

Shipping from 1 repo is much easier, but if we're talking about merging 2 repos, even though it doesn't look too difficult, I'm not sure how much time I can spare for it.

2022-01-17 20:16 UTC, ciuliano-shopify approved these changes
LGTM!
Seems odd to me that this rule lives outside of the Web repository though.
I sent you a DM on Slack about the approach - I think we might not need a lint rule if we handle this differently but IDK for sure.

2022-01-17 22:17 UTC, BPScott commented
> You mean moving this whole project to web, or only what I'm adding?

I meant define this one lint rule into web, as this lint rule is only applicable in this the web repository. Putting something that only applies to a single repository into a config that is applicable to multiple projects feels strange. Web-specific things should go in web.

> And may I ask where we add these rules to web?

We don't currently have a folder for this sort of thing. But with [impending work](https://github.com/Shopify/web/issues/55393) we'll need somewhere to put build/test/lint tooling config. Perhaps we create a new top level folder for storing general build config, then this could live in `build-config/eslint/rules/jsx-no-hardcoded-admin-prefix`?


> Shipping from 1 repo is much easier, but if we're talking about merging 2 repos, even though it doesn't look too difficult, I'm not sure how much time I can spare for it.

You wouldn't need to port across all the existing content in the eslint-plugin package. Just add this rule into web, instead of here.

2022-01-17 22:19 UTC, BPScott requested changes
Marking this as "request changes" while we work out if this could live directly in the web repository instead of putting a web-specific rule into pan organisation config.

2022-01-17 23:31 UTC, ttemrahcelik commented
> You wouldn't need to port across all the existing content in the eslint-plugin package. Just add this rule into web, instead of here.

ok i'm all for this. just wanted to make sure if this whole `web-configs` project is web specific or not. 🍻

2022-01-17 23:33 UTC, BPScott commented
> just wanted to make sure if this whole web-configs project is web specific or not. 

Stuff in this repo is org-wide :) The eternally confusing question "does web mean web as a discipline within shopify, or just the admin web codebase" strikes again.

2022-01-18 18:23 UTC, ttemrahcelik commented
Closing this in favour of adding the rule as part of: https://github.com/Shopify/web/pull/55083

2022-01-18 18:23 UTC, closed without merging